name: 'Destroy Terraform resources'

on: workflow_dispatch

env:
  TF_BACKEND_BUCKET_NAME: ${{ vars.TF_BACKEND_BUCKET_NAME }}
  TF_BACKEND_BUCKET_KEY: ${{ vars.TF_BACKEND_BUCKET_KEY }}
  TF_BACKEND_BUCKET_REGION: ${{ vars.TF_BACKEND_BUCKET_REGION }}

permissions:
  contents: read

jobs:
  destroy-resources:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: make init
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Destroy
      run: |
        make destroy
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Remove terraform resources"
        git checkout -b remove/terraform-resources
        git push origin remove/terraform-resources
        gh pr create --base main --head remove/terraform-resources --title "Remove terraform resources" --body "Remove terraform resources that were destroyed"
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}