name: 'Validate users config file'

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate-users-config:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go 1.21.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4

      - name: Display Go version
        run: go version

      - name: Run script
        run: |
          make check_resources